metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
    process.include_top_n:
      by_cpu: 5
      by_memory: 5

  - module: postgresql
    enabled: true
    metricsets:
      - database
      - bgwriter
      - activity
    period: 10s
    hosts: ["postgres://postgres:postgres@pgpool:5432/edufarm?sslmode=disable"]

  - module: redis
    enabled: true
    metricsets: ["info", "keyspace"]
    period: 10s
    hosts: ["redis:6379"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "metricbeat-edufarm-%{+yyyy.MM.dd}"

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_host_metadata: ~

setup.kibana:
  host: "kibana:5601"
